version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hive

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadata:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASWORD: root
      MYSQL_DATABASE: hive
      MYSQL_ROOT_PASSWORD: root
  
  redis:
    image: redis
    ports:
      - 6379:6379
      

volumes:
  pgdata:
  mariadata:
